### ISSUE TITLE
[POL-73] [POL-72] Figure out "migrations" for topics

### ISSUE THREAD

**Issue by tg339** [514-labs/igloo-stack#25]
This should probably include defining a schema for the red panda schema registry to enable data quality enforcement. As I've dug into this it seems like protobufs will be a requirement to be able to enforce schemas in the registry. This is something we've talked about in the past. Given that we're hoping for multi language support, it may make sense to leverage \~\~\~\~\~\~protobufs\~\~\~\~\~\~ avro as the cross-language serialization it may make sense to make avro easy to work with.

<sub>From [SyncLinear.com](https://synclinear.com) | [POL-72](https://linear.app/polarizedcapital/issue/POL-72/figure-out-migrations-for-topics)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [POL-72](https://linear.app/polarizedcapital/issue/POL-72/figure-out-migrations-for-topics)</sub>

**Comment by tg339** [comment]
@nic would love your thoughts here

**Comment by nic** [comment]
LGTM 👍

**Comment by tg339** [comment]
As I've explored even more, it's becoming evident that there's easy fix here. The capabilities that we want are the capabilities of a full featured ORM but specific to a streaming & OLAP environment. From what I've gathered, we could use AVRO schemas as the base modeling capability and then build an ORM like capability around Avro

**Comment by nic** [comment]
Hey @allicles, we would love to hear your thoughts here!
