### ISSUE TITLE
[POL-54] Ingestion point abstraction

### ISSUE THREAD

**Issue by tg339** [514-labs/igloo-stack#3]
<sub>From [SyncLinear.com](https://synclinear.com) | [POL-54](https://linear.app/polarizedcapital/issue/POL-54/ingestion-point-abstraction)</sub>

**Comment by tg339** [comment]
It seems like protobuf "migrations" could possibly enable us to kill two birds with one stone on both the database migration side of the house and the schema registry for redpanda. It may enable us to speed up cross language support as well.

**Comment by tg339** [comment]
@nic curious to get your thoughts here

**Comment by tg339** [comment]
the interaction could be something like this: 

```
$ igloo add ingestion-point --name=user-event -a=timestamp:utc -a=packet:json -a=type:enum
```

**Comment by tg339** [comment]
this interaction would then create the ingestion point template for the user, the protobuf and the necessary scripts for both database migration and schema registration

**Comment by nic** [comment]
Looks good to me! :+1:

**Comment by tg339** [comment]
The main issue that we seem to have to solve is the web developer's interaction with the protobufs and how they'll write code against it. It's unclear if that's an intuitive way of working for them and exactly what the workflow will look like
